// Generated by CoffeeScript 1.5.0
(function() {

  $(function() {
    var terms;
    return terms = chrome.tabs.query({
      "active": true,
      "currentWindow": true
    }, function(tab) {
      return chrome.tabs.sendMessage(tab[0].id, "stuff", function(response) {
        var term, _i, _len, _results;
        console.log(JSON.stringify(response));
        terms = response;
        _results = [];
        for (_i = 0, _len = terms.length; _i < _len; _i++) {
          term = terms[_i];
          _results.push($(".terms").append($('<li></li>', {
            "class": "term",
            "text": "" + term
          })));
        }
        return _results;
      });
    });
  });

}).call(this);
