// Generated by CoffeeScript 1.5.0
(function() {

  $(function() {
    var article, articles, articlesArray, articlesLength, _i, _len, _results;
    if ($('#queue').length > 0) {
      articles = $('#queue');
      articlesLength = articles.children().length;
      articlesArray = articles.children();
      debugger;
      _results = [];
      for (_i = 0, _len = articlesArray.length; _i < _len; _i++) {
        article = articlesArray[_i];
        _results.push(console.log("article!"));
      }
      return _results;
    }
  });

}).call(this);
